Document: nginx-letsencrypt
Title: Debian nginx-letsencrypt Manual
Author: <insert document author here>
Abstract: This manual describes what nginx-letsencrypt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nginx-letsencrypt/nginx-letsencrypt.sgml.gz

Format: postscript
Files: /usr/share/doc/nginx-letsencrypt/nginx-letsencrypt.ps.gz

Format: text
Files: /usr/share/doc/nginx-letsencrypt/nginx-letsencrypt.text.gz

Format: HTML
Index: /usr/share/doc/nginx-letsencrypt/html/index.html
Files: /usr/share/doc/nginx-letsencrypt/html/*.html
